In [1]:
import tensorflow as tf

print(f'tensorflow version {tf.__version__}')

from imblearn.over_sampling import SMOTE
from collections import Counter
from numpy import * 

import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

tensorflow version 2.9.1


# Loading the Data & Smote

In [2]:
def dataLoadSm():
    test = pd.read_csv('Real_Tomorrow/test_real_tom_target.csv')
    train = pd.read_csv('Real_Tomorrow/training_real_tom_target.csv')
    val = pd.read_csv('Real_Tomorrow/validation_real_tom_target.csv')
    print(train.head())
    
    #Split data
    x_train = train[[ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']]
    print ("******training features******")
    print (x_train)
    y_train = train[['Real_tom_lsm']]
    print ("******training target******")
    print (y_train)
    
    x_test = test[[ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']]
    print ("******test features******")
    print (x_test)
    y_test = test[['Real_tom_lsm']]
    print ("******test target******")
    print (y_test)
    
    x_val = val[[ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']]
    print ("******validation features******")
    print (x_val)
    y_val = val[['Real_tom_lsm']]
    print ("******validation target******")
    print (y_val)
    
    print('Before Smote')

    dff = y_train
    M = y_train.to_numpy()
    # summarize dataset
    classes = unique(M)
    print(classes)
    total = len(M)
    for c in classes:
        n_examples = len(M[M==c])
        percent = n_examples / total * 100
        print('> Class=%d : %d/%d (%.1f%%)' % (c, n_examples, total, percent))
    
    
    smt = SMOTE()
    
    X_train_sm, Y_train_sm = smt.fit_resample(x_train, y_train)
    
    print('After SMOTE')
    dff = Y_train_sm
    M = Y_train_sm.to_numpy()
    # summarize dataset
    classes = unique(M)
    print(classes)
    total = len(M)
    for c in classes:
        n_examples = len(M[M==c])
        percent = n_examples / total * 100
        print('> Class=%d : %d/%d (%.1f%%)' % (c, n_examples, total, percent))
        
    return X_train_sm, Y_train_sm, x_val, y_val, x_test, y_test

def dataLoad():
    test = pd.read_csv('Real_Tomorrow/test_real_tom_target.csv')
    train = pd.read_csv('Real_Tomorrow/training_real_tom_target.csv')
    val = pd.read_csv('Real_Tomorrow/validation_real_tom_target.csv')
    print(train.head())
    
    #Split data
    x_train = train[[ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']]
    print ("******training features******")
    #print (x_train)
    y_train = train[['Real_tom_lsm']]
    print ("******training target******")
    #print (y_train)
    
    x_test = test[[ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']]
    print ("******test features******")
    #print (x_test)
    y_test = test[['Real_tom_lsm']]
    print ("******test target******")
    #print (y_test)
    
    x_val = val[[ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']]
    print ("******validation features******")
    #print (x_val)
    y_val = val[['Real_tom_lsm']]
    print ("******validation target******")
    #print (y_val)
    
        
    return x_train, y_train, x_val, y_val, x_test, y_test

In [3]:
x_train_sm, y_train_sm, x_val, y_val, x_test, y_test = dataLoadSm()
x_train, y_train, x_val, y_val, x_test, y_test = dataLoad()


   Unnamed: 0        time  latitude  longitude        vo          r     u_200  \
0           0  1980-01-01       0.0       20.0  0.000007  80.761185  1.909660   
1           1  1980-01-01       0.0       22.5  0.000004  80.703650  1.165733   
2           2  1980-01-01       0.0       25.0  0.000007  78.231514 -1.311676   
3           3  1980-01-01       0.0       27.5  0.000010  79.631010 -3.777573   
4           4  1980-01-01       0.0       30.0  0.000010  71.573875 -5.734505   

      u_850     v_200     v_850        ttr  sst  lsm  Real_tom_lsm  
0 -3.323872  1.687164 -1.823624 -247.54074  0.0  0.0           0.0  
1 -2.844494  1.060593 -1.991425 -240.00592  0.0  0.0           0.0  
2 -2.125244  3.280617 -1.931789 -223.76889  0.0  0.0           0.0  
3 -1.122395  5.743889 -1.243538 -235.55556  0.0  0.0           0.0  
4 -1.362953  6.514030 -0.954163 -254.03260  0.0  0.0           0.0  
******training features******
               vo          r      u_200     u_850      v_200     v_85

# Standardization

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#scaled_x_training = scaler.fit_transform(x_training)
#df = pd.DataFrame(StandardScaler().fit_transform(x_training))

X_train_stand = x_train_sm.copy() #smote
X_valid_stand = x_val.copy() #smote
X_test_stand = x_test.copy() #smote

#not smote
X_train_scaled = x_train.copy() 
X_valid_scaled = x_val.copy()
X_test_scaled = x_test.copy()

num_cols = [ 'vo', 'r', 'u_200', 'u_850', 'v_200','v_850', 'ttr','sst']

# apply standardization on numerical features
for i in num_cols:
    
    # fit on training data column
    scale = StandardScaler().fit(X_train_stand[[i]])
    
    # transform the training data column
    X_train_stand[i] = scale.transform(X_train_stand[[i]])
    
    # transform the training data column
    X_valid_stand[i] = scale.transform(X_valid_stand[[i]])   

    # transform the testing data column
    X_test_stand[i] = scale.transform(X_test_stand[[i]])
    
for i in num_cols:
    
    # fit on training data column
    scale = StandardScaler().fit(X_train_scaled[[i]])
    
    # transform the training data column
    X_train_scaled[i] = scale.transform(X_train_scaled[[i]])
    
    # transform the training data column
    X_valid_scaled[i] = scale.transform(X_valid_scaled[[i]])   

    # transform the testing data column
    X_test_scaled[i] = scale.transform(X_test_scaled [[i]])

# ExtraTreesClassifier

In [21]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import log_loss
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import confusion_matrix

# get a list of models to evaluate
def get_models():
    models = dict()
    n_trees = [10, 50, 100, 500, 1000, 5000]
    min_samples_leaf = [1, 10, 50, 100, 500, 1000, 5000]
    max_features= ['sqrt', 'log2', None] 
    for n in n_trees:
        for l in min_samples_leaf:
            for m in max_features:
                models[str(n)+'trees_'+str(l)+'leafSamples_'+str(m)+'maxFeat'] = ExtraTreesClassifier(criterion='log_loss', n_estimators=n, min_samples_leaf=l, max_features=m)
    return models

#ExtraTreesClassifier_class_weight
def get_models_class_weight(method):
    models = dict()
    n_trees = [10, 50, 100, 500, 1000, 5000]
    min_samples_leaf = [1, 10, 50, 100, 500, 1000, 5000]
    max_features= ['sqrt', 'log2', None] 
    
    if method == 'balanced':
        print("The “balanced” mode uses the values of y to automatically adjust weights inversely proportional to class frequencies in the input data as n_samples / (n_classes * np.bincount(y))")
        for n in n_trees:
        for l in min_samples_leaf:
            for m in max_features:
                models[str(n)+'trees_'+str(l)+'leafSamples_'+str(m)+'maxFeat'] = ExtraTreesClassifier(criterion='log_loss', n_estimators=n, min_samples_leaf=l, max_features=m, class_weight="balanced")
    elif method == 'balanced_subsample':
        print("The “balanced_subsample” mode is the same as “balanced” except that weights are computed based on the bootstrap sample for every tree grown.")
        for n in n_trees:
        for l in min_samples_leaf:
            for m in max_features:
                models[str(n)+'trees_'+str(l)+'leafSamples_'+str(m)+'maxFeat'] = ExtraTreesClassifier(criterion='log_loss', n_estimators=n, min_samples_leaf=l, max_features=m, class_weight="balanced_subsample")
    else:
        print('the method is not callable')
    return models
# evaluate a given model using validation
def evaluate_model(model, x_train, y_train, x_val, y_val):
    trained_mod = model.fit(x_train, y_train)
    score = log_loss(y_val, model.predict_proba(x_val))
    conf = confusion_matrix(y_val, np.round(model.predict(x_val)))
    np.set_printoptions(precision=2)
    print(conf)  
    return score

# models


In [22]:
models = get_models()


# random_forest_smote

In [ ]:
results, names = list(), list()
for name, model in models.items():
    score = evaluate_model(model, X_train_stand, y_train_sm.values.reshape(-1,), X_valid_stand, y_val.values.reshape(-1,))

    results.append(score)
    names.append(name)

[[685156   2007]
 [   688    551]]
[[685141   2022]
 [   702    537]]
[[685130   2033]
 [   702    537]]
[[666563  20600]
 [   256    983]]
[[672805  14358]
 [   290    949]]
[[677411   9752]
 [   361    878]]
[[643813  43350]
 [   166   1073]]
[[658143  29020]
 [   185   1054]]
[[665353  21810]
 [   226   1013]]
[[641443  45720]
 [   152   1087]]
[[651627  35536]
 [   157   1082]]
[[658499  28664]
 [   178   1061]]
[[620232  66931]
 [   137   1102]]
[[634127  53036]
 [   143   1096]]
[[641803  45360]
 [   139   1100]]
[[613746  73417]
 [   134   1105]]
[[631884  55279]
 [   152   1087]]
[[635871  51292]
 [   134   1105]]
[[588180  98983]
 [   163   1076]]
[[600488  86675]
 [   152   1087]]
[[625320  61843]
 [   122   1117]]
[[685265   1898]
 [   639    600]]
[[685302   1861]
 [   668    571]]
[[685183   1980]
 [   676    563]]
[[669971  17192]
 [   249    990]]


# ExtraTreesClassifier_class_weight

In [19]:
logistic_regression_with_val(X_train_scaled,y_train,X_valid_scaled,y_val)

##########################Penalty:l1, solver:newton-cg, C100##########################
##########################Penalty:l1, solver:lbfgs, C100##########################
##########################Penalty:l1, solver:liblinear, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705726  0.28400323  0.14547696 -0.68773563 -0.03177079  0.07213172
   0.88752071  0.67371025]]
[-7.5923385]
##########################Penalty:l1, solver:sag, C100##########################
##########################Penalty:l1, solver:saga, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.4170667   0.28398066  0.14547838 -0.68774149 -0.03177496  0.07213486
   0.88754934  0.67370835]]
[-7.59234049]
##########################Penalty:l2, solver:newton-cg, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705791  0.2839768   0.14547938 -0.6877359  -0.03177514  0.07213429
   0.88753968  0.67370754]]
[-7.59234403]
##########################Penalty:l2, solver:lbfgs, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705449  0.28396658  0.1455216  -0.68776023 -0.03170367  0.07217787
   0.88755892  0.67370233]]
[-7.59236155]
##########################Penalty:l2, solver:liblinear, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705889  0.28401585  0.14549499 -0.68774001 -0.03175846  0.07213448
   0.88750147  0.6736203 ]]
[-7.5922363]
##########################Penalty:l2, solver:sag, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706431  0.28396404  0.14547957 -0.68771842 -0.03177094  0.07215578
   0.88755631  0.67367689]]
[-7.59228958]
##########################Penalty:l2, solver:saga, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706676  0.28398426  0.14548161 -0.68774121 -0.03177647  0.07213627
   0.88754882  0.67370979]]
[-7.59234242]
##########################Penalty:elasticnet, solver:newton-cg, C100##########################
##########################Penalty:elasticnet, solver:lbfgs, C100##########################
##########################Penalty:elasticnet, solver:liblinear, C100##########################
##########################Penalty:elasticnet, solver:sag, C100##########################
##########################Penalty:elasticnet, solver:saga, C100##########################
##########################Penalty:none, solver:newton-cg, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705783  0.28397728  0.14548047 -0.68773644 -0.03177453  0.07213456
   0.88754029  0.67371017]]
[-7.59234631]
##########################Penalty:none, solver:lbfgs, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705441  0.28396706  0.14552268 -0.68776078 -0.03170306  0.07217815
   0.88755953  0.67370496]]
[-7.59236383]
##########################Penalty:none, solver:liblinear, C100##########################
##########################Penalty:none, solver:sag, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706423  0.28396452  0.14548065 -0.68771896 -0.03177032  0.07215606
   0.88755692  0.67367951]]
[-7.59229183]
##########################Penalty:none, solver:saga, C100##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706668  0.28398474  0.14548269 -0.68774176 -0.03177587  0.07213654
   0.88754942  0.67371242]]
[-7.59234469]
##########################Penalty:l1, solver:newton-cg, C10##########################
##########################Penalty:l1, solver:lbfgs, C10##########################
##########################Penalty:l1, solver:liblinear, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705678  0.28395641  0.14543782 -0.68772968 -0.03176086  0.07211514
   0.88751445  0.67365908]]
[-7.59225972]
##########################Penalty:l1, solver:sag, C10##########################
##########################Penalty:l1, solver:saga, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706684  0.28394393  0.14543954 -0.68773909 -0.03176679  0.07211973
   0.88754861  0.67367176]]
[-7.59230262]
##########################Penalty:l2, solver:newton-cg, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/scipy/optimize/linesearch.py:437: LineSearchWarning: Rounding errors prevent the line search from converging
  warn(msg, LineSearchWarning)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/scipy/optimize/linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/optimize.py:203: UserWarning: Line Search failed
  warnings.warn("Line Search failed")
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validatio

[[-0.41705864  0.28397248  0.14546968 -0.68773101 -0.03178058  0.07213186
   0.88753428  0.67368383]]
[-7.59232356]
##########################Penalty:l2, solver:lbfgs, C10##########################
[[-0.41705522  0.2839623   0.14551187 -0.68775533 -0.03170915  0.07217542
   0.88755351  0.67367865]]
[-7.59234112]
##########################Penalty:l2, solver:liblinear, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705494  0.28393492  0.14548291 -0.68770817 -0.03175062  0.072121
   0.88745405  0.67348609]]
[-7.59190532]
##########################Penalty:l2, solver:sag, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706496  0.2839598   0.1454698  -0.68771354 -0.03177645  0.07215326
   0.88755081  0.6736533 ]]
[-7.59226926]
##########################Penalty:l2, solver:saga, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706748  0.28397995  0.14547186 -0.6877363  -0.03178194  0.07213382
   0.88754336  0.67368612]]
[-7.59232192]
##########################Penalty:elasticnet, solver:newton-cg, C10##########################
##########################Penalty:elasticnet, solver:lbfgs, C10##########################
##########################Penalty:elasticnet, solver:liblinear, C10##########################
##########################Penalty:elasticnet, solver:sag, C10##########################
##########################Penalty:elasticnet, solver:saga, C10##########################
##########################Penalty:none, solver:newton-cg, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705783  0.28397728  0.14548047 -0.68773644 -0.03177453  0.07213456
   0.88754029  0.67371017]]
[-7.59234631]
##########################Penalty:none, solver:lbfgs, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705441  0.28396706  0.14552268 -0.68776078 -0.03170306  0.07217815
   0.88755953  0.67370496]]
[-7.59236383]
##########################Penalty:none, solver:liblinear, C10##########################
##########################Penalty:none, solver:sag, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706423  0.28396452  0.14548065 -0.68771896 -0.03177032  0.07215606
   0.88755692  0.67367951]]
[-7.59229183]
##########################Penalty:none, solver:saga, C10##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706668  0.28398474  0.14548269 -0.68774176 -0.03177587  0.07213654
   0.88754942  0.67371242]]
[-7.59234469]
##########################Penalty:l1, solver:newton-cg, C1.0##########################
##########################Penalty:l1, solver:lbfgs, C1.0##########################
##########################Penalty:l1, solver:liblinear, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705205  0.28348837  0.14504647 -0.68767016 -0.03166156  0.07194932
   0.88745183  0.67314774]]
[-7.59147236]
##########################Penalty:l1, solver:sag, C1.0##########################
##########################Penalty:l1, solver:saga, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706827  0.28357659  0.14505113 -0.68771502 -0.03168503  0.07196842
   0.88754135  0.67330594]]
[-7.59192416]
##########################Penalty:l2, solver:newton-cg, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/scipy/optimize/linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/optimize.py:203: UserWarning: Line Search failed
  warnings.warn("Line Search failed")


[[-0.41706587  0.28392948  0.14537222 -0.68768193 -0.03183523  0.07210738
   0.88747986  0.67344732]]
[-7.59211871]
##########################Penalty:l2, solver:lbfgs, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706244  0.28391953  0.14541458 -0.6877063  -0.03176388  0.07215091
   0.88749933  0.67344203]]
[-7.59213682]
##########################Penalty:l2, solver:liblinear, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41701537  0.28312825  0.14536228 -0.68739011 -0.03167237  0.07198639
   0.8869804   0.67214856]]
[-7.58860304]
##########################Penalty:l2, solver:sag, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41707155  0.28391738  0.14537223 -0.68766481 -0.03183155  0.07212804
   0.88749582  0.67341755]]
[-7.59206614]
##########################Penalty:l2, solver:saga, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41707468  0.2839369   0.14537437 -0.68768719 -0.0318366   0.07210938
   0.88748885  0.67344961]]
[-7.59211709]
##########################Penalty:elasticnet, solver:newton-cg, C1.0##########################
##########################Penalty:elasticnet, solver:lbfgs, C1.0##########################
##########################Penalty:elasticnet, solver:liblinear, C1.0##########################
##########################Penalty:elasticnet, solver:sag, C1.0##########################
##########################Penalty:elasticnet, solver:saga, C1.0##########################
##########################Penalty:none, solver:newton-cg, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705783  0.28397728  0.14548047 -0.68773644 -0.03177453  0.07213456
   0.88754029  0.67371017]]
[-7.59234631]
##########################Penalty:none, solver:lbfgs, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705441  0.28396706  0.14552268 -0.68776078 -0.03170306  0.07217815
   0.88755953  0.67370496]]
[-7.59236383]
##########################Penalty:none, solver:liblinear, C1.0##########################
##########################Penalty:none, solver:sag, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706423  0.28396452  0.14548065 -0.68771896 -0.03177032  0.07215606
   0.88755692  0.67367951]]
[-7.59229183]
##########################Penalty:none, solver:saga, C1.0##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706668  0.28398474  0.14548269 -0.68774176 -0.03177587  0.07213654
   0.88754942  0.67371242]]
[-7.59234469]
##########################Penalty:l1, solver:newton-cg, C0.1##########################
##########################Penalty:l1, solver:lbfgs, C0.1##########################
##########################Penalty:l1, solver:liblinear, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41700519  0.27882087  0.14113819 -0.68707584 -0.03066904  0.07029317
   0.88682725  0.66806698]]
[-7.58364291]
##########################Penalty:l1, solver:sag, C0.1##########################
##########################Penalty:l1, solver:saga, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41708299  0.279904    0.14116459 -0.68747546 -0.03086572  0.070455
   0.8874697   0.66966   ]]
[-7.58815777]
##########################Penalty:l2, solver:newton-cg, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/scipy/optimize/linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/optimize.py:203: UserWarning: Line Search failed
  warnings.warn("Line Search failed")
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.4171379   0.28350297  0.14440223 -0.68719138 -0.03237872  0.07186339
   0.88693584  0.67109777]]
[-7.59007924]
##########################Penalty:l2, solver:lbfgs, C0.1##########################
[[-0.41713447  0.28349449  0.1444462  -0.68721645 -0.03230827  0.07190486
   0.88695807  0.67109108]]
[-7.59010211]
##########################Penalty:l2, solver:liblinear, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41661943  0.275314    0.14417996 -0.68423445 -0.03090875  0.07066219
   0.88229252  0.65920904]]
[-7.55631099]
##########################Penalty:l2, solver:sag, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41713856  0.2834956   0.14440155 -0.68717766 -0.03237842  0.07187794
   0.88694726  0.67107526]]
[-7.59004186]
##########################Penalty:l2, solver:saga, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41714638  0.28350979  0.14440406 -0.68719635 -0.03238015  0.07186562
   0.88694393  0.67109996]]
[-7.59007783]
##########################Penalty:elasticnet, solver:newton-cg, C0.1##########################
##########################Penalty:elasticnet, solver:lbfgs, C0.1##########################
##########################Penalty:elasticnet, solver:liblinear, C0.1##########################
##########################Penalty:elasticnet, solver:sag, C0.1##########################
##########################Penalty:elasticnet, solver:saga, C0.1##########################
##########################Penalty:none, solver:newton-cg, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705783  0.28397728  0.14548047 -0.68773644 -0.03177453  0.07213456
   0.88754029  0.67371017]]
[-7.59234631]
##########################Penalty:none, solver:lbfgs, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705441  0.28396706  0.14552268 -0.68776078 -0.03170306  0.07217815
   0.88755953  0.67370496]]
[-7.59236383]
##########################Penalty:none, solver:liblinear, C0.1##########################
##########################Penalty:none, solver:sag, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706423  0.28396452  0.14548065 -0.68771896 -0.03177032  0.07215606
   0.88755692  0.67367951]]
[-7.59229183]
##########################Penalty:none, solver:saga, C0.1##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706668  0.28398474  0.14548269 -0.68774176 -0.03177587  0.07213654
   0.88754942  0.67371242]]
[-7.59234469]
##########################Penalty:l1, solver:newton-cg, C0.01##########################
##########################Penalty:l1, solver:lbfgs, C0.01##########################
##########################Penalty:l1, solver:liblinear, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41658299  0.23339021  0.10257062 -0.68121133 -0.02079336  0.05392689
   0.88073801  0.62027034]]
[-7.50952498]
##########################Penalty:l1, solver:sag, C0.01##########################
##########################Penalty:l1, solver:saga, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41727479  0.24325384  0.10205536 -0.68518557 -0.02249468  0.05529087
   0.88685561  0.63436129]]
[-7.55228286]
##########################Penalty:l2, solver:newton-cg, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41782843  0.27955479  0.13513854 -0.68231531 -0.03753046  0.06949773
   0.88152026  0.64902989]]
[-7.57053029]
##########################Penalty:l2, solver:lbfgs, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41782998  0.2795387   0.13518138 -0.68233898 -0.03747817  0.06950593
   0.88154821  0.64903031]]
[-7.57056453]
##########################Penalty:l2, solver:liblinear, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41266407  0.21595605  0.13428814 -0.6549175  -0.02477069  0.05921787
   0.83971687  0.56113528]]
[-7.28907477]
##########################Penalty:l2, solver:sag, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41781699  0.27950913  0.13512469 -0.68235853 -0.03753208  0.06954015
   0.88148525  0.64902113]]
[-7.57051852]
##########################Penalty:l2, solver:saga, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41783759  0.2795603   0.13513978 -0.68227228 -0.03754868  0.06937359
   0.88151619  0.64902008]]
[-7.5705141]
##########################Penalty:elasticnet, solver:newton-cg, C0.01##########################
##########################Penalty:elasticnet, solver:lbfgs, C0.01##########################
##########################Penalty:elasticnet, solver:liblinear, C0.01##########################
##########################Penalty:elasticnet, solver:sag, C0.01##########################
##########################Penalty:elasticnet, solver:saga, C0.01##########################
##########################Penalty:none, solver:newton-cg, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705783  0.28397728  0.14548047 -0.68773644 -0.03177453  0.07213456
   0.88754029  0.67371017]]
[-7.59234631]
##########################Penalty:none, solver:lbfgs, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41705441  0.28396706  0.14552268 -0.68776078 -0.03170306  0.07217815
   0.88755953  0.67370496]]
[-7.59236383]
##########################Penalty:none, solver:liblinear, C0.01##########################
##########################Penalty:none, solver:sag, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706423  0.28396452  0.14548065 -0.68771896 -0.03177032  0.07215606
   0.88755692  0.67367951]]
[-7.59229183]
##########################Penalty:none, solver:saga, C0.01##########################


/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1113: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  warnings.warn(
/Users/3rfanian/opt/anaconda3/envs/SHAP/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.41706668  0.28398474  0.14548269 -0.68774176 -0.03177587  0.07213654
   0.88754942  0.67371242]]
[-7.59234469]
