In [1]:
import numpy as np
import pandas as pd

In [39]:
df = pd.read_csv("/work/bk1318/b382633/data_csv/predictors_v2_dailymean_1/train_dailymeans_Sindian.csv")

In [40]:
df

Unnamed: 0  latitude  longitude        time            vo  \
0                  0       0.0       20.0  1980-01-01  5.569600e-06   
1                  1       0.0       21.0  1980-01-01  5.180307e-06   
2                  2       0.0       22.0  1980-01-01  7.108611e-06   
3                  3       0.0       23.0  1980-01-01  5.136069e-06   
4                  4       0.0       24.0  1980-01-01  8.465082e-06   
...              ...       ...        ...         ...           ...   
24921918    24921918     -30.0       86.0  2010-12-31  1.378897e-05   
24921919    24921919     -30.0       87.0  2010-12-31  6.994596e-06   
24921920    24921920     -30.0       88.0  2010-12-31  2.247543e-07   
24921921    24921921     -30.0       89.0  2010-12-31 -1.446708e-06   
24921922    24921922     -30.0       90.0  2010-12-31  4.839603e-06   

                  r      u_200     u_850      v_200     v_850        sst  \
0         82.019554   1.696365 -3.273395   1.873566 -1.849995    0.00000   
1         82.263664   2.182632 -3.134358   2.011780 -1.815815    0.00000   
2         81.370040   1.560501 -2.855091   0.978851 -1.855793    0.00000   
3         80.632250   1.032577 -2.823017   0.986481 -1.920673    0.00000   
4         78.985060   0.400375 -2.533344   1.489441 -2.129414    0.00000   
...             ...        ...       ...        ...       ...        ...   
24921918  24.548264  24.870674 -2.889652 -10.818787  0.573387  295.14502   
24921919  26.298523  25.089676 -2.873802 -10.910202  0.978970  295.18793   
24921920  25.693947  25.138329 -2.899319 -10.960007  0.609791  295.11050   
24921921  20.860558  24.961770 -3.154552 -10.642502  0.059662  294.89157   
24921922  15.684181  24.534485 -3.577686 -10.158928 -0.259968  294.51044   

               tcwv      tclw      tciw      shear  
0         45.304337  0.105498  0.023871   6.209946  
1         44.427475  0.106129  0.011709   6.551402  
2         43.985610  0.103364  0.003874   5.247158  
3         43.609756  0.115436  0.006961   4.828784  
4         44.109573  0.109886  0.029762   4.658628  
...             ...       ...       ...        ...  
24921918  23.070324  0.048457  0.000000  30.006956  
24921919  22.705334  0.054363  0.000000  30.385992  
24921920  21.300358  0.056044  0.000000  30.331005  
24921921  20.064625  0.058250  0.000000  30.084278  
24921922  19.663937  0.045217  0.000000  29.804087  

[24921923 rows x 15 columns]

In [56]:
df_test = pd.read_csv("/work/bk1318/b382633/data_csv/predictors_v2_dailymean_1/test_dailymeans_Sindian.csv")

In [57]:
df_test

Unnamed: 0  latitude  longitude        time        vo          r  \
0                 0       0.0       20.0  2016-04-01  0.000003  82.689590   
1                 1       0.0       21.0  2016-04-01  0.000011  87.146570   
2                 2       0.0       22.0  2016-04-01 -0.000001  78.225174   
3                 3       0.0       23.0  2016-04-01 -0.000003  71.998116   
4                 4       0.0       24.0  2016-04-01  0.000009  75.876660   
...             ...       ...        ...         ...       ...        ...   
5427661     5427661     -30.0       86.0  2022-12-31 -0.000003   9.031833   
5427662     5427662     -30.0       87.0  2022-12-31 -0.000011   8.893886   
5427663     5427663     -30.0       88.0  2022-12-31 -0.000012   8.432330   
5427664     5427664     -30.0       89.0  2022-12-31 -0.000004   7.901454   
5427665     5427665     -30.0       90.0  2022-12-31  0.000001   7.244884   

             u_200     u_850      v_200     v_850        sst       tcwv  \
0        -8.812576  5.084553   2.345459  1.971470    0.00000  54.418915   
1        -8.011398  5.256611   3.138763  2.215855    0.00000  55.497444   
2        -6.580460  4.879414   4.114227  2.208469    0.00000  54.159424   
3        -5.942734  3.040512   4.309387  1.333908    0.00000  52.304413   
4        -4.980728  2.609726   4.615143 -0.201687    0.00000  52.471832   
...            ...       ...        ...       ...        ...        ...   
5427661  16.882332 -3.579315  12.766792  2.521202  294.51056  17.570087   
5427662  18.081985 -3.472538  13.955536  2.601090  294.43110  16.723050   
5427663  19.658860 -3.230461  14.706093  2.636833  294.62433  16.259120   
5427664  21.486374 -3.037853  15.900650  2.755791  294.43643  16.251629   
5427665  23.343560 -3.006729  17.414139  3.101067  294.01830  16.327389   

             tclw      tciw      shear  
0        0.075203  0.042222  13.902161  
1        0.078448  0.093240  13.300069  
2        0.051347  0.190273  11.617254  
3        0.102467  0.296958   9.463202  
4        0.295514  0.447555   8.989819  
...           ...       ...        ...  
5427661  0.026339  0.000204  22.883425  
5427662  0.026032  0.000406  24.362286  
5427663  0.038844  0.001524  25.876398  
5427664  0.049453  0.002759  27.824902  
5427665  0.054230  0.003089  29.986692  

[5427666 rows x 15 columns]

In [41]:
train_data = np.load("/work/bk1318/b382633/data_npy/npy_1/Sindian_train_img_std.npy")
train_data.shape

(11323, 31, 71, 11)

In [42]:
y_train = np.load("/work/bk1318/b382633/data_npy/npy_1/Sindian_y_train_img.npy")
y_train.shape

(11323, 13, 29, 1)

In [59]:
test_data = np.load("/work/bk1318/b382633/data_npy/npy_1/Sindian_test_img_std.npy")
test_data.shape

(2466, 31, 71, 11)

In [43]:
train_data.shape[1]

31

In [44]:
df.iloc[[0]]

Unnamed: 0  latitude  longitude        time        vo          r     u_200  \
0           0       0.0       20.0  1980-01-01  0.000006  82.019554  1.696365   

      u_850     v_200     v_850  sst       tcwv      tclw      tciw     shear  
0 -3.273395  1.873566 -1.849995  0.0  45.304337  0.105498  0.023871  6.209946

In [45]:
train_data[0][0][0]

array([ 0.29333255,  1.38700013, -0.37832757, -0.13514163,  0.4423622 ,
       -0.72848423, -1.63138384,  0.85446492,  1.04751618,  0.20289345,
       -1.11493302])

In [46]:
train_data[:,:,:,[0,1]]

array([[[[ 2.93332547e-01,  1.38700013e+00],
         [ 2.71752950e-01,  1.39635479e+00],
         [ 3.78644200e-01,  1.36210978e+00],
         ...,
         [ 1.69043012e+00,  1.14166194e+00],
         [ 1.41113455e+00,  1.08326972e+00],
         [ 9.65294104e-01,  1.02722132e+00]],

        [[ 5.91771662e-01,  1.29995271e+00],
         [ 2.28109793e-01,  1.34527707e+00],
         [ 6.15003984e-02,  1.32539818e+00],
         ...,
         [ 2.40115943e+00,  1.30691955e+00],
         [ 1.67764954e+00,  1.24055975e+00],
         [ 1.15323460e+00,  1.17085257e+00]],

        [[ 5.19805320e-01,  1.28105791e+00],
         [ 5.64964974e-01,  1.25390062e+00],
         [ 3.58219733e-01,  1.20585849e+00],
         ...,
         [ 9.90445513e-01,  1.25721274e+00],
         [ 5.05614637e-01,  1.27430260e+00],
         [ 7.15416160e-02,  1.22772090e+00]],

        ...,

        [[ 1.00191938e+00, -1.03464822e+00],
         [ 1.89584037e-01, -9.15951916e-01],
         [-7.14558152e-01, -8.93306442

In [47]:
df.iloc[[0], 4:15]

vo          r     u_200     u_850     v_200     v_850  sst  \
0  0.000006  82.019554  1.696365 -3.273395  1.873566 -1.849995  0.0   

        tcwv      tclw      tciw     shear  
0  45.304337  0.105498  0.023871  6.209946

In [60]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
std_data = df.iloc[:, 4:15]
std_data = scaler.fit_transform(df.iloc[:, 4:15])
std_data_test = scaler.transform(df_test.iloc[:, 4:15])
std_data[0]

array([ 0.29333255,  1.38700013, -0.37832757, -0.13514163,  0.4423622 ,
       -0.72848423, -1.63138384,  0.85446492,  1.04751618,  0.20289345,
       -1.11493302])

In [49]:
train_data[0][0][5]

array([ 0.35649672,  1.2211664 , -0.54903744,  0.13451991,  0.59171823,
       -0.79857216, -1.63138384,  0.76781287,  0.96980635,  0.76112117,
       -1.18811864])

In [50]:
std_data[5]

array([ 0.35649672,  1.2211664 , -0.54903744,  0.13451991,  0.59171823,
       -0.79857216, -1.63138384,  0.76781287,  0.96980635,  0.76112117,
       -1.18811864])

In [61]:
test_data[0][0][5]

array([ 1.52177835,  1.15162112, -0.5584225 ,  1.26686422,  0.65632932,
        0.02280483, -1.63138384,  1.44004337,  4.5616705 , 12.26164681,
       -1.14890275])

In [62]:
std_data_test[5]

array([ 1.52177835,  1.15162112, -0.5584225 ,  1.26686422,  0.65632932,
        0.02280483, -1.63138384,  1.44004337,  4.5616705 , 12.26164681,
       -1.14890275])

In [51]:
train_data[0][1][0]

array([ 0.59177166,  1.29995271, -0.4193    , -0.01634239,  0.46105357,
       -0.60608982, -1.63138384,  0.99080149,  1.10906344,  1.03969581,
       -1.21051414])

In [52]:
std_data[29]

array([ 0.42268103, -0.8010591 , -0.95669056, -0.38416946,  0.66918656,
       -1.34081456,  0.62135677,  0.79289747, -0.34346647, -0.39685835,
       -0.90101825])

In [53]:
std_data[71]

array([ 0.59177166,  1.29995271, -0.4193    , -0.01634239,  0.46105357,
       -0.60608982, -1.63138384,  0.99080149,  1.10906344,  1.03969581,
       -1.21051414])

In [54]:
train_data[-1][-1][-1]

array([ 0.25286678, -1.15507045,  0.92037789, -0.19711115, -0.9654025 ,
       -0.29927387,  0.57766167, -1.09070228, -0.18244748, -0.40803679,
        0.78067031])

In [55]:
std_data[-1]

array([ 0.25286678, -1.15507045,  0.92037789, -0.19711115, -0.9654025 ,
       -0.29927387,  0.57766167, -1.09070228, -0.18244748, -0.40803679,
        0.78067031])

In [20]:
import pandas as pd
pd.options.display.max_columns = None
pd.set_option('display.max_rows', 150)
import numpy as np
import argparse

import decimal
from decimal import Decimal

import matplotlib.pyplot as plt

from pathlib import Path  

from sklearn.model_selection import train_test_split # for splitting the data into train and test samples
from sklearn.metrics import classification_report # for model evaluation metrics
from sklearn.preprocessing import OrdinalEncoder # for encoding labels
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import confusion_matrix
from sklearn.utils.class_weight import compute_sample_weight

#from imblearn.over_sampling import SMOTE
from collections import Counter
import io
import requests
from sklearn import metrics

from sklearn.metrics import roc_curve, auc
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.calibration import CalibrationDisplay
from sklearn.metrics import brier_score_loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow import keras
from keras import Sequential # for creating a linear stack of layers for our Neural Network
from keras import Input # for instantiating a keras tensor
from keras.layers import Dense # for creating regular densely-connected NN layer.
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout # for adding Concolutional and densely-connected NN layers.
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Input, Flatten,\
                                    Reshape, LeakyReLU as LR,\
                                    Activation, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dropout,BatchNormalization,Conv2D,MaxPooling2D,Dense,Flatten
from tensorflow.keras.datasets import cifar10
from tensorflow.keras import regularizers
from keras import callbacks
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
import matplotlib.pyplot as plt
from keras.layers import Dense # for creating regular densely-connected NN layer.
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout,MaxPooling2D # for adding Concolutional and densely-connected NN layers.
from tensorflow.keras import layers
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Activation, Dropout
from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda, Cropping2D

2023-12-27 22:31:48.918490: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [29]:
def simple_unet_model(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS):
#Build the model
    inputs = Input((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))
    #s = Lambda(lambda x: x / 255)(inputs)   #No need for this if we normalize our inputs beforehand
    s = inputs

    #Contraction path
    c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(s)
    c1 = Dropout(0.1)(c1)
    c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c1)
    p1 = MaxPooling2D((2, 2))(c1)
    
    c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p1)
    c2 = Dropout(0.1)(c2)
    c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c2)
    p2 = MaxPooling2D((2, 2))(c2)
     
    c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p2)
    c3 = Dropout(0.2)(c3)
    c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c3)
    p3 = MaxPooling2D((2, 2))(c3)
     
    c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p3)
    c4 = Dropout(0.2)(c4)
    c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c4)
    p4 = MaxPooling2D(pool_size=(2, 2))(c4)
     
    c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p4)
    c5 = Dropout(0.3)(c5)
    c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c5)
    
    #Expansive path 
    u6 = Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(c5)
    u6 = concatenate([u6, c4])
    c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u6)
    c6 = Dropout(0.2)(c6)
    c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c6)
     
    u7 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c6)
    u7 = concatenate([u7, c3])
    c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u7)
    c7 = Dropout(0.2)(c7)
    c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c7)
     
    u8 = Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(c7)
    u8 = concatenate([u8, c2])
    c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u8)
    c8 = Dropout(0.1)(c8)
    c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c8)
     
    u9 = Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same')(c8)
    u9 = concatenate([u9, c1], axis=3)
    c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u9)
    c9 = Dropout(0.1)(c9)
    c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c9)
    
    c10 = Cropping2D(cropping=((1,2),(1,2)))(c9)
     
    outputs = Conv2D(1, (1, 1), activation='sigmoid')(c10)
     
    model = Model(inputs=[inputs], outputs=[outputs])
    
    #model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.summary()
    
    return model

In [31]:
model = simple_unet_model(16,32,9)

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 16, 32, 9)]  0           []                               
                                                                                                  
 conv2d_8 (Conv2D)              (None, 16, 32, 16)   1312        ['input_2[0][0]']                
                                                                                                  
 dropout_4 (Dropout)            (None, 16, 32, 16)   0           ['conv2d_8[0][0]']               
                                                                                                  
 conv2d_9 (Conv2D)              (None, 16, 32, 16)   2320        ['dropout_4[0][0]']              
                                                                                              